// Realistic seed dataset for E-Outpass Management System
// Designed for hostel administration testing and viva evaluation

const initialOutpasses = [
  {
    id: "OP-2026-001",
    studentId: "23IT101",
    studentName: "Keertheswar S",
    department: "Information Technology",
    year: "3rd Year",
    hostelBlock: "Block A (Boys)",
    roomNumber: "A-304",
    studentPhone: "+91 98765 43210",
    parentName: "Senthil Nathan (Father)",
    parentPhone: "+91 94432 10987",
    parentConsent: "CONFIRMED_VIA_SMS",
    outpassType: "WEEKEND_PASS",
    destination: "Trichy (Native Place)",
    reason: "Going home for family function and weekend break.",
    departureTime: new Date(Date.now() + 2 * 3600 * 1000).toISOString(),
    expectedReturnTime: new Date(Date.now() + 52 * 3600 * 1000).toISOString(),
    actualReturnTime: null,
    status: "PENDING",
    wardenRemarks: "",
    reviewedBy: "",
    reviewedAt: null,
    createdAt: new Date(Date.now() - 35 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 35 * 60 * 1000).toISOString(),
    gatePassToken: null,
    studentHistory: {
      totalOutpassesThisSem: 3,
      onTimeReturns: 3,
      overstays: 0,
      cgpa: "8.82",
      attendance: "94%"
    }
  },
  {
    id: "OP-2026-002",
    studentId: "23CS142",
    studentName: "Priya Dharshini M",
    department: "Computer Science and Engineering",
    year: "3rd Year",
    hostelBlock: "Block B (Girls)",
    roomNumber: "B-214",
    studentPhone: "+91 97890 12345",
    parentName: "Meenakshi Sundaram (Father)",
    parentPhone: "+91 94876 54321",
    parentConsent: "VERIFIED",
    outpassType: "EMERGENCY_PASS",
    destination: "Apollo Clinic / Apollo Pharmacy, Gandhipuram",
    reason: "Severe dental toothache, scheduled appointment with dentist Dr. Balaji at 4:30 PM.",
    departureTime: new Date(Date.now() + 1 * 3600 * 1000).toISOString(),
    expectedReturnTime: new Date(Date.now() + 5 * 3600 * 1000).toISOString(),
    actualReturnTime: null,
    status: "PENDING",
    wardenRemarks: "",
    reviewedBy: "",
    reviewedAt: null,
    createdAt: new Date(Date.now() - 12 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 12 * 60 * 1000).toISOString(),
    gatePassToken: null,
    studentHistory: {
      totalOutpassesThisSem: 2,
      onTimeReturns: 2,
      overstays: 0,
      cgpa: "9.15",
      attendance: "96%"
    }
  },
  {
    id: "OP-2026-003",
    studentId: "22EC088",
    studentName: "Arvind Kumar R",
    department: "Electronics & Communication",
    year: "4th Year",
    hostelBlock: "Block A (Boys)",
    roomNumber: "A-118",
    studentPhone: "+91 91234 56780",
    parentName: "R. Radhakrishnan (Father)",
    parentPhone: "+91 93456 78901",
    parentConsent: "PENDING_CALL",
    outpassType: "DAY_PASS",
    destination: "Town Hall & Electronics Hardware Market",
    reason: "Purchasing sensors, Arduino microcontrollers, and PCB components for final year capstone project.",
    departureTime: new Date(Date.now() + 3 * 3600 * 1000).toISOString(),
    expectedReturnTime: new Date(Date.now() + 8 * 3600 * 1000).toISOString(),
    actualReturnTime: null,
    status: "PENDING",
    wardenRemarks: "",
    reviewedBy: "",
    reviewedAt: null,
    createdAt: new Date(Date.now() - 55 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 55 * 60 * 1000).toISOString(),
    gatePassToken: null,
    studentHistory: {
      totalOutpassesThisSem: 5,
      onTimeReturns: 4,
      overstays: 1,
      cgpa: "7.90",
      attendance: "87%"
    }
  },
  {
    id: "OP-2026-004",
    studentId: "23AI015",
    studentName: "Sneha Nair",
    department: "Artificial Intelligence & Data Science",
    year: "2nd Year",
    hostelBlock: "Block B (Girls)",
    roomNumber: "B-108",
    studentPhone: "+91 98945 61234",
    parentName: "S. Nair (Father)",
    parentPhone: "+91 97861 23456",
    parentConsent: "VERIFIED",
    outpassType: "WEEKEND_PASS",
    destination: "Palakkad, Kerala",
    reason: "Sister's engagement ceremony at hometown.",
    departureTime: new Date(Date.now() + 6 * 3600 * 1000).toISOString(),
    expectedReturnTime: new Date(Date.now() + 60 * 3600 * 1000).toISOString(),
    actualReturnTime: null,
    status: "PENDING",
    wardenRemarks: "",
    reviewedBy: "",
    reviewedAt: null,
    createdAt: new Date(Date.now() - 90 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 90 * 60 * 1000).toISOString(),
    gatePassToken: null,
    studentHistory: {
      totalOutpassesThisSem: 1,
      onTimeReturns: 1,
      overstays: 0,
      cgpa: "8.75",
      attendance: "92%"
    }
  },
  {
    id: "OP-2026-005",
    studentId: "23ME034",
    studentName: "Mohammed Faizal",
    department: "Mechanical Engineering",
    year: "3rd Year",
    hostelBlock: "Block C (Boys)",
    roomNumber: "C-204",
    studentPhone: "+91 96551 23478",
    parentName: "A. Abdul Faizal (Father)",
    parentPhone: "+91 99441 23890",
    parentConsent: "PENDING_CALL",
    outpassType: "DAY_PASS",
    destination: "PSG Tech Campus (Inter-College Hackathon)",
    reason: "Representing college at 24-hour CAD design and prototyping challenge.",
    departureTime: new Date(Date.now() + 4 * 3600 * 1000).toISOString(),
    expectedReturnTime: new Date(Date.now() + 28 * 3600 * 1000).toISOString(),
    actualReturnTime: null,
    status: "PENDING",
    wardenRemarks: "",
    reviewedBy: "",
    reviewedAt: null,
    createdAt: new Date(Date.now() - 110 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 110 * 60 * 1000).toISOString(),
    gatePassToken: null,
    studentHistory: {
      totalOutpassesThisSem: 4,
      onTimeReturns: 4,
      overstays: 0,
      cgpa: "8.40",
      attendance: "91%"
    }
  },
  {
    id: "OP-2026-006",
    studentId: "22IT115",
    studentName: "Deepa Lakshmi V",
    department: "Information Technology",
    year: "4th Year",
    hostelBlock: "Block B (Girls)",
    roomNumber: "B-305",
    studentPhone: "+91 98421 98765",
    parentName: "V. Vijayaraghavan (Father)",
    parentPhone: "+91 94422 33445",
    parentConsent: "VERIFIED",
    outpassType: "DAY_PASS",
    destination: "Coimbatore Railway Station",
    reason: "Receiving grandmother coming by Shatabdi Express.",
    departureTime: new Date(Date.now() - 4 * 3600 * 1000).toISOString(),
    expectedReturnTime: new Date(Date.now() + 4 * 3600 * 1000).toISOString(),
    actualReturnTime: null,
    status: "APPROVED",
    wardenRemarks: "Parent approved over phone. Return before 8:30 PM gate close.",
    reviewedBy: "Dr. S. Meenakshi (Hostel Warden)",
    reviewedAt: new Date(Date.now() - 4 * 3600 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 5 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 4 * 3600 * 1000).toISOString(),
    gatePassToken: "EOP-SEC-8921",
    studentHistory: {
      totalOutpassesThisSem: 2,
      onTimeReturns: 2,
      overstays: 0,
      cgpa: "8.95",
      attendance: "95%"
    }
  },
  // 7. Boys Block A - Karthik Raja P
  {
    id: "OP-2026-007",
    studentId: "24CS045",
    studentName: "Karthik Raja P",
    department: "Computer Science",
    year: "1st Year",
    hostelBlock: "Block A (Boys)",
    roomNumber: "A-105",
    studentPhone: "+91 98401 23456",
    parentName: "P. Palanisamy (Father)",
    parentPhone: "+91 94441 55667",
    parentConsent: "VERIFIED",
    outpassType: "EMERGENCY_PASS",
    destination: "Eye Foundation Hospital, RS Puram",
    reason: "Eye irritation and urgent ophthalmology checkup.",
    departureTime: new Date(Date.now() + 1 * 3600 * 1000).toISOString(),
    expectedReturnTime: new Date(Date.now() + 4 * 3600 * 1000).toISOString(),
    actualReturnTime: null,
    status: "PENDING",
    wardenRemarks: "",
    reviewedBy: "",
    reviewedAt: null,
    createdAt: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
    gatePassToken: null,
    studentHistory: {
      totalOutpassesThisSem: 1,
      onTimeReturns: 1,
      overstays: 0,
      cgpa: "8.20",
      attendance: "93%"
    }
  },
  // 8. Girls Block D - Ananya Ramesh
  {
    id: "OP-2026-008",
    studentId: "23BT028",
    studentName: "Ananya Ramesh",
    department: "Biotechnology",
    year: "3rd Year",
    hostelBlock: "Block D (Girls)",
    roomNumber: "D-201",
    studentPhone: "+91 97900 11223",
    parentName: "Ramesh K (Father)",
    parentPhone: "+91 94433 88990",
    parentConsent: "VERIFIED",
    outpassType: "WEEKEND_PASS",
    destination: "Salem (Native Home)",
    reason: "Attending family festival celebration with relatives.",
    departureTime: new Date(Date.now() + 5 * 3600 * 1000).toISOString(),
    expectedReturnTime: new Date(Date.now() + 50 * 3600 * 1000).toISOString(),
    actualReturnTime: null,
    status: "PENDING",
    wardenRemarks: "",
    reviewedBy: "",
    reviewedAt: null,
    createdAt: new Date(Date.now() - 40 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 40 * 60 * 1000).toISOString(),
    gatePassToken: null,
    studentHistory: {
      totalOutpassesThisSem: 2,
      onTimeReturns: 2,
      overstays: 0,
      cgpa: "9.05",
      attendance: "97%"
    }
  },
  // 9. Boys Block C - Sanjay V (Approved)
  {
    id: "OP-2026-009",
    studentId: "23EE062",
    studentName: "Sanjay V",
    department: "Electrical & Electronics",
    year: "3rd Year",
    hostelBlock: "Block C (Boys)",
    roomNumber: "C-312",
    studentPhone: "+91 99440 98765",
    parentName: "V. Velmurugan (Father)",
    parentPhone: "+91 98411 77889",
    parentConsent: "VERIFIED",
    outpassType: "DAY_PASS",
    destination: "Local Power Substation / Industrial Visit",
    reason: "Field study for electrical power transmission project.",
    departureTime: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    expectedReturnTime: new Date(Date.now() + 4 * 3600 * 1000).toISOString(),
    actualReturnTime: null,
    status: "APPROVED",
    wardenRemarks: "Permission granted for academic study.",
    reviewedBy: "Dr. R. Sundaram (Chief Warden)",
    reviewedAt: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 3 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    gatePassToken: "EOP-SEC-5542",
    studentHistory: {
      totalOutpassesThisSem: 3,
      onTimeReturns: 3,
      overstays: 0,
      cgpa: "8.65",
      attendance: "92%"
    }
  },
  // 10. Girls Block D - Kavitha S
  {
    id: "OP-2026-010",
    studentId: "24EC071",
    studentName: "Kavitha S",
    department: "Electronics & Communication",
    year: "2nd Year",
    hostelBlock: "Block D (Girls)",
    roomNumber: "D-115",
    studentPhone: "+91 94455 66778",
    parentName: "S. Shanmugam (Father)",
    parentPhone: "+91 98402 33445",
    parentConsent: "PENDING_CALL",
    outpassType: "DAY_PASS",
    destination: "Cross Cut Road Market",
    reason: "Purchasing books and hostel essentials.",
    departureTime: new Date(Date.now() + 2 * 3600 * 1000).toISOString(),
    expectedReturnTime: new Date(Date.now() + 6 * 3600 * 1000).toISOString(),
    actualReturnTime: null,
    status: "PENDING",
    wardenRemarks: "",
    reviewedBy: "",
    reviewedAt: null,
    createdAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    gatePassToken: null,
    studentHistory: {
      totalOutpassesThisSem: 1,
      onTimeReturns: 1,
      overstays: 0,
      cgpa: "8.40",
      attendance: "89%"
    }
  }
];

module.exports = { initialOutpasses };
