"""create outpasses table

Revision ID: 32bbc6315f8b
Revises: 
Create Date: 2026-09-11 13:46:03.433288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32bbc6315f8b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outpasses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(length=20), nullable=False),
    sa.Column('destination', sa.String(length=200), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('departure_datetime', sa.DateTime(), nullable=False),
    sa.Column('return_datetime', sa.DateTime(), nullable=False),
    sa.Column('parent_contact', sa.String(length=15), nullable=False),
    sa.Column('request_timestamp', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('warden_remarks', sa.Text(), nullable=True),
    sa.Column('decision_timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outpasses_id'), 'outpasses', ['id'], unique=False)
    op.create_index(op.f('ix_outpasses_student_id'), 'outpasses', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outpasses_student_id'), table_name='outpasses')
    op.drop_index(op.f('ix_outpasses_id'), table_name='outpasses')
    op.drop_table('outpasses')
    # ### end Alembic commands ###
